# Generated by Django 5.2.5 on 2025-08-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='titile',
            new_name='title',
        ),
    ]
